// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://egyeaxrzesbhqwsypxak.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVneWVheHJ6ZXNiaHF3c3lweGFrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkwNDg5NTAsImV4cCI6MjA3NDYyNDk1MH0.APOkWcs6kH0vIGGqLEOda0jXv-zZEaEx3VcozNi4VEY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});